// Generated by CoffeeScript 1.6.3
(function() {
  var bgclicked, clicked, dummyEventHandler, getMouseX, getMouseY, hour, min, mousedown, mousedownbg, mousedownbg_old, mousedownx, mousedowny, mousemove, mouseup, mousex, mousey, newhour, newmin, newsec, sec, settable, settime, timetable;

  hour = 12;

  min = 0;

  sec = 0;

  newhour = 12;

  newmin = 0;

  newsec = 0;

  dummyEventHandler = function(event) {};

  settime = function(hour, min, sec) {
    var totalsec, x;
    $('#hour').text(hour);
    $('#min').text(('0' + min).slice(-2));
    $('#sec').text(('0' + sec).slice(-2));
    totalsec = ((hour * 60 + min) * 60) + sec;
    x = totalsec / 4 / 80;
    $('#knob').css('left', x + 13);
    $('#time').css('top', 46);
    return $('#time').css('left', x + 2);
  };

  mousedownx = 0;

  mousedowny = 0;

  mousex = 0;

  mousey = 0;

  clicked = false;

  bgclicked = false;

  timetable = [];

  getMouseX = function(e) {
    return e.pageX;
  };

  getMouseY = function(e) {
    return e.pageY;
  };

  settable = function(hour, min, sec) {
    var h, i, ind, m, s, _i, _results;
    ind = 0;
    timetable = [];
    timetable[ind] = [hour, min, sec];
    h = hour;
    m = min;
    s = sec;
    ind--;
    timetable[ind] = [h, m, s];
    for (i = _i = 0; _i < 10; i = ++_i) {
      if (s > 0) {
        s -= 1;
      } else {
        if (m > 0) {
          m -= 1;
          s = 59;
        } else {
          if (h > 0) {
            h -= 1;
            m = 59;
            s = 59;
          }
        }
      }
      timetable[--ind] = [h, m, s];
      timetable[--ind] = [h, m, s];
    }
    [0, 1, 2, 3, 4, 5, 6, 7].forEach(function(i) {
      if (s % 10 !== 0) {
        s = s - s % 10;
      } else {
        if (s > 0) {
          s -= 10;
        } else {
          if (m > 0) {
            m -= 1;
            s = 50;
          } else {
            if (h > 0) {
              h -= 1;
              m = 59;
              s = 50;
            }
          }
        }
      }
      timetable[--ind] = [h, m, s];
      timetable[--ind] = [h, m, s];
      return timetable[--ind] = [h, m, s];
    });
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].forEach(function(i) {
      if (m > 0) {
        m -= 1;
        s = 0;
      } else {
        if (h > 0) {
          h -= 1;
          m = 59;
          s = 0;
        }
      }
      timetable[--ind] = [h, m, s];
      return timetable[--ind] = [h, m, s];
    });
    [0, 1, 2, 3, 4, 5, 6, 7].forEach(function(i) {
      if (m % 10 !== 0) {
        m = m - m % 10;
        s = 0;
      } else {
        if (m > 0) {
          m -= 10;
          s = 0;
        } else {
          if (h > 0) {
            h -= 1;
            m = 50;
            s = 0;
          }
        }
      }
      timetable[--ind] = [h, m, s];
      timetable[--ind] = [h, m, s];
      return timetable[--ind] = [h, m, s];
    });
    while (true) {
      if (m % 60 !== 0) {
        m = 0;
        s = 0;
      } else {
        if (h > 0) {
          h -= 1;
          m = 0;
          s = 0;
        }
      }
      timetable[--ind] = [h, m, s];
      timetable[--ind] = [h, m, s];
      timetable[--ind] = [h, m, s];
      timetable[--ind] = [h, m, s];
      if (h === 0) {
        break;
      }
    }
    h = hour;
    m = min;
    s = sec;
    ind = 0;
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].forEach(function(i) {
      if (s < 59) {
        s += 1;
      } else {
        if (m < 59) {
          m += 1;
          s = 0;
        } else {
          if (h < 23) {
            h += 1;
            m = 0;
            s = 0;
          } else {
            h = 24;
            m = 0;
            s = 0;
          }
        }
      }
      timetable[++ind] = [h, m, s];
      return timetable[++ind] = [h, m, s];
    });
    [0, 1, 2, 3, 4, 5, 6, 7].forEach(function(i) {
      if (s % 10 !== 0) {
        s = s - s % 10;
        if (s === 50) {
          if (m < 59) {
            m += 1;
            s = 0;
          }
        } else {
          s += 10;
        }
      } else {
        if (s < 50) {
          s += 10;
        } else {
          if (m < 59) {
            m += 1;
            s = 0;
          } else {
            if (h < 23) {
              h += 1;
              m = 0;
              s = 0;
            } else {
              h = 24;
              m = 0;
              s = 0;
            }
          }
        }
      }
      timetable[++ind] = [h, m, s];
      timetable[++ind] = [h, m, s];
      return timetable[++ind] = [h, m, s];
    });
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].forEach(function(i) {
      if (m < 59) {
        m += 1;
        s = 0;
      } else {
        if (h < 23) {
          h += 1;
          m = 0;
          s = 0;
        } else {
          h = 24;
          m = 0;
          s = 0;
        }
      }
      timetable[++ind] = [h, m, s];
      return timetable[++ind] = [h, m, s];
    });
    [0, 1, 2, 3, 4, 5, 6, 7].forEach(function(i) {
      if (m % 10 !== 0) {
        m = m - m % 10;
        if (m === 50) {
          if (h < 23) {
            h += 1;
            m = 0;
            s = 0;
          }
        } else {
          m += 10;
          s = 0;
        }
      } else {
        if (m < 50) {
          m += 10;
          s = 0;
        } else {
          if (h < 23) {
            h += 1;
            m = 0;
            s = 0;
          } else {
            h = 24;
            m = 0;
            s = 0;
          }
        }
      }
      timetable[++ind] = [h, m, s];
      timetable[++ind] = [h, m, s];
      return timetable[++ind] = [h, m, s];
    });
    _results = [];
    while (true) {
      if (m % 60 !== 0) {
        if (h < 23) {
          h += 1;
          m = 0;
          s = 0;
        } else {
          m = 59;
          s = 59;
        }
      } else {
        if (h < 23) {
          h += 1;
          m = 0;
          s = 0;
        } else {
          h = 24;
          m = 0;
          s = 0;
        }
      }
      timetable[++ind] = [h, m, s];
      timetable[++ind] = [h, m, s];
      timetable[++ind] = [h, m, s];
      timetable[++ind] = [h, m, s];
      if (h === 24 && m === 0 && s === 0) {
        break;
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  mousedown = function(event) {
    clicked = true;
    mousedownx = getMouseX(event);
    mousedowny = getMouseX(event);
    mousex = mousedownx;
    mousey = mousedowny;
    newhour = hour;
    newmin = min;
    newsec = sec;
    settime(newhour, newmin, newsec);
    settable(newhour, newmin, newsec);
    return false;
  };

  mousedownbg = function(event) {
    bgclicked = true;
    mousedownx = getMouseX(event);
    mousedowny = getMouseX(event);
    mousex = mousedownx;
    mousey = mousedowny;
    newhour = hour;
    newmin = min;
    newsec = sec;
    settime(newhour, newmin, newsec);
    settable(newhour, newmin, newsec);
    return false;
  };

  mousedownbg_old = function(event) {
    var offsetx;
    clicked = true;
    mousedownx = getMouseX(event);
    mousedowny = getMouseX(event);
    mousex = mousedownx;
    mousey = mousedowny;
    offsetx = document.getElementById('slider').offsetLeft;
    newhour = Math.floor((mousex - offsetx - 10) / 12);
    if (newhour < 0) {
      newhour = 0;
    }
    if (newhour >= 24) {
      newhour = 23;
    }
    newmin = 0;
    newsec = 0;
    settime(newhour, newmin, newsec);
    settable(newhour, newmin, newsec);
    return false;
  };

  mousemove = function(event) {
    var ind, t, _ref;
    event.preventDefault();
    mousedownx = getMouseX(event);
    mousedowny = getMouseX(event);
    if (clicked) {
      ind = mousedownx - mousex;
      if (ind !== 0) {
        t = ((hour * 60 + min) * 60) + sec;
        t += ind * 320;
        t = Math.floor((t + 300) / 600) * 600;
        newsec = 0;
        newhour = Math.floor(t / 3600);
        if (t < 0) {
          newhour = 0;
          newmin = 0;
          newsec = 0;
        } else if (newhour >= 24) {
          newhour = 24;
          newmin = 0;
          newsec = 0;
        } else {
          newmin = Math.floor((t - newhour * 3600) / 60);
          newsec = 0;
        }
        settime(newhour, newmin, newsec);
      }
    }
    if (bgclicked) {
      ind = mousedownx - mousex;
      if (timetable[ind]) {
        settime(timetable[ind][0], timetable[ind][1], timetable[ind][2]);
        _ref = timetable[ind], newhour = _ref[0], newmin = _ref[1], newsec = _ref[2];
      }
    }
    return false;
  };

  mouseup = function(event) {
    hour = newhour;
    min = newmin;
    sec = newsec;
    clicked = false;
    bgclicked = false;
    return false;
  };

  $(function() {
    settime(12, 0, 0);
    $('body').on('click', dummyEventHandler);
    $('#knob').on('mousedown', mousedown);
    $('#knobbg').on('mousedown', mousedownbg);
    $('#slider').on('mousedown', function(event) {
      event.preventDefault();
      return mousedownbg(event);
    });
    $(document).on('mousemove', mousemove);
    return $(document).on('mouseup', mouseup);
  });

}).call(this);
